alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
alias psql='/usr/local/pgsql-9.1/bin/psql'
alias utc='date -u'
alias papertrail='heroku addons:open papertrail'
alias newrelic='heroku addons:open newrelic'
